#port configuration
server:
  port: 80

#thymeleaf
spring:

  #resources
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #mvc
  mvc:
    log-request-details: true

  #http
  http:
    multipart:
      enabled: true

  thymeleaf:
    prefix: /WEB-INF/views/
    suffix: .jsp
  devtools:
    add-properties: true
  #jpa properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true
    hibernate:
      ddl-auto: none
  #database configuration
  datasource:
    name: election_commission
    url: jdbc:postgresql://localhost:5432/election_commission
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialize: true
  #flyway
  flyway:
    baseline-on-migrate: false
  web:
    resources:
      static-locations: file:${user.dir}/src/main/webapp/static

logging:
  level:
    springframework:
      jdbc:
        core:
          JdbcTemplate: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor: DEBUG
    web: DEBUG

#flyway
flyway:
  enabled: true

jwt:
  secret: javainusejavainusejavainusejavainusejavainusejavainusejavainusejavainusejavainusejavainusejavainusejavainuse

