#port configuration
server:
  port: 8082

#thymeleaf
spring:
  thymeleaf:
    prefix: /WEB-INF/views/
    suffix: .jsp
  devtools:
    add-properties: true
  jpa:
    open-in-view: false
logging:
  level:
    web: DEBUG

#dev properties
