version: '3.1'
services:
  electioncommission:
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    container_name: electioncommission
    ports:
      - "80:80"
      - "5432:5432"
#    network_mode: host
    environment:
      - SPRING_DATASOURCE_URL= jdbc:postgresql:// 127.0.0.1:5432/postgres
